# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='joined_by',
            field=models.ManyToManyField(related_name='trips_joined', to='login_app.User'),
        ),
    ]
